version: "3"
services:
  cassandra:
    container_name: cassandra-container
    image: cassandra:latest
    networks: [sklep_network]
  sklep:
    container_name: pis-sklep
    build:
      context: .
      dockerfile: backend/sklep/Dockerfile
    image: pis-sklep:latest
    networks: [sklep_network]
    restart: unless-stopped
    depends_on: [cassandra]

networks:
  sklep_network:
    name: sklep_network
