version: "3"
services:
  frontend:
    container_name: nodejs-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: nodejs-frontend:latest
    networks: [sklep_network]
    ports:
      - "3000:3000"

  cassandra:
    container_name: cassandra-container
    image: cassandra:latest
    networks: [sklep_network]
  sklep:
    container_name: pis-sklep
    build:
      context: .
      dockerfile: backend/sklep/Dockerfile
    
    # ports:
    #   - "8080:8080"
    image: pis-sklep:latest
    networks: [sklep_network]
    restart: unless-stopped
    depends_on: [cassandra]

networks:
  sklep_network:
    name: sklep_network
