version: "3"
services:
  frontend:
    container_name: nginx-react-app
    image: nginx:latest
    networks: [sklep_network]
    ports:
      - "8080:8080"
    volumes:
      - ./ngnix:/etc/nginx/conf.d
      - ./frontend/build:/app/static

  cassandra:
    container_name: cassandra-container
    image: cassandra:latest
    networks: [sklep_network]
    ports:
      - "9042:9042"
  sklep:
    container_name: pis-sklep
    build:
      context: .
      dockerfile: backend/sklep/Dockerfile
    
    ports:
       - "1234:1234" #api, z ktorym rozmawia frontend
    image: pis-sklep:latest
    networks: [sklep_network]
    restart: unless-stopped
    depends_on: [cassandra]

networks:
  sklep_network:
    name: sklep_network
